
import React, { Component } from 'react';
export const data = [
  {
    recipeId: 1,
    recipeName: "Oreo Thick Shake",
    recipeImage:<img src="" />,
    recipeIngredients: "Oreo cookies, one glass cold milk, Hershey’s chocolate syrup, One scoop chocolate ice cream, Sugar according to your taste, Ice cubes",
    recipePrepTime: "10 minutes",
    recipeMethod: "Step 1 . Add small packet of Oreo cookies with one glass of milk in the blender. Step 2 . Add sugar (According to your taste ) in the blender. Step 3 . Add Hershey’s chocolate syrup 2 – 3 tsp and ice cubes in the blender. Step 4 . Add one Scoop of chocolate ice-cream in blender and blend it. Step 5 . Now Oreo thick shake is ready. Step 6 . Decorate the glass with chocolate syrup. Step 7 . Pour the Oreo thick shake in a decorated glass. Step 8 . Garnish it with Crushed one piece of Oreo cookies and chocolate syrup.",
    recipeSuggestion: "You can garnish it with whipped cream." ,
  }, 
  {
    recipeId: 2,
    recipeName: "Veg. Hakka Noodles",
    recipeImage:<img src="http://www.blog.sagmart.com/wp-content/uploads/2015/07/Hakka-Noodles.jpg"  width="47.5%" height="30%"  />,
    recipeIngredients: "for boiling noodles: 8 cup water, 2 tbsp oil, 1 tsp salt, 2 pack noodles, for hakka noodles: 2 tbsp oil, 2 clove garlic (finely chopped), 1 chilli (slit), 2 inch ginger (chopped), 2 tbsp spring onion (chopped), ½ onion (sliced), ½ capsicum (sliced), ½ cabbage (shredded), 1 carrot (sliced), 2 beans (chopped), 2 tbsp chilli sauce, 2 tbsp soy sauce, 2 tbsp tomato sauce, ½ tsp salt, ½ tsp pepper powder, 2 tbsp vinegar, few bean sprouts",
    recipePrepTime: "20 mins",
    recipeMethod: "Step 1 . firstly, in a large vessel take 8 cup water, 2 tbsp oil, 1 tsp salt. Step 2 . once the water comes to a boil, add 2 pack noodles. Step 3 . stir and boil for 3 minutes or until the noodles turn al dente. refer package instructions to know the cooking time. Step 4 . drain off the noodles and rinse with cold water to stop the cooking process. keep aside. Step 5 . in a large wok heat 2 tbsp oil and add 2 clove garlic, 1 chilli, 2 inch ginger and 2 tbsp spring onion. Step 6 . stir fry on high flame. Step 7 . now add ½ onion, ½ capsicum, ½ cabbage, 1 carrot, 2 beans. stir fry until the vegetables shrink slightly. Step 8 . further add 2 tbsp chilli sauce, 2 tbsp soy sauce, 2 tbsp tomato sauce, ½ tsp salt and ½ tsp pepper powder. Step 9 . stir fry until the sauces well combine. Step 10 . now add boiled noodles, 2 tbsp vinegar and stir fry. Step 11 . also add few bean sprouts and 2 tbsp spring onions. stir fry. Step 12 . veg hakka noodles is ready. garnish it with more spring onions.",
    recipeSuggestion: " ",
  },
  {
  recipeId: 3,
    recipeName: "Rasgulla",
    recipeImage: <img src="https://4.imimg.com/data4/IJ/JR/MY-11458628/spongy-rasgulla-500x500.jpg" />,
    recipeIngredients: "one litre full fat milk, 2 tbps lemon juice or vinegar, cold water, thin cloth, 2 cups of sugar, 1 litre water, cardamoms, 2 tsp rose water, kesar",
    recipePrepTime: "1 hour",
    recipeMethod: "Step 1 . First rinse a heavy bottom utensil to boil milk. By rinsing, you can prevent the milk from being burnt beneath. Pour the 1 litre milk and bring it to a boil over a medium high heat. Keep stirring to prevent a layer of cream forming on top. Step 2 . Pour 2 tbps of lemon juice or vinegar. Step 3 . keep stirring. The milk will begin to curdle. Turn off the stove and stir well until it curdles completely. If it doesn't then add another tbsp of lemon juice. Step 4 . Next pour ice cold water or add ice cubes. This helps to stop the cheese from further cooking. This way it stays soft. Step 5 . Allow to rest for 2 minutes. Step 6 . Immediately pour to a colander lined with a thin cloth. Immediately rinse it well to remove the lemon flavor. Step 7 . Wrap the chenna in the cloth and rinse well under running water until it cools down. Step 8 . Make a knot of the cloth. Sqeeze up and remove as much excess water as possible. Then hang it on a hook for 30 to 40 minutes. I felt the timing depends on the kind of milk. Sometimes Ieven leave up to 1 to 1.5 hours. Step 9 . The chenna after draining the whey must be moist and should not have dripping water or whey in it. Excess whey may impact the rasgulla in 2 ways - i) May disintegrate the rasgulla in syrup. ii) The rasgullas may double in size but will shrink once taken off the heat. Step 10 . The entire chhena should look crumbly and grainy. Begin to knead with your fingers until it turns smooth and uniform. This may take up to 3 to 5 minutes. I usually do it only for 3 mins with the use of homogenised milk. If the chenna is very grainy then you may need to knead it for 5 mins. Step 11 . Just aim to get uniformly smooth chenna and do not over knead. Over kneading may shrink the rasgullas imediately after taking off the heat. Step 12 . Divide the dough to 18 portions. Make smooth balls that are crack free. Do not make them large as they will double in size when cooked. Cover these and set aside. Step 13 . Add sugar to a wide pot. Choosing the right size of the pot is also very important. I used a mini pressure pan here but used a 4 litre pot other times. The pan must be wide enough for the rasgullas to move around and puff well. Similarly it must be deep enough. Step 14 . Pour water and add cardamom pods. I prefer pods than powder as it keeps the syrup clear. Step  15 . Dissolve the sugar and bring it to a rolling boil. Then remove the cardamoms and add some rose water. The flame has to be medium to medium high, such that the syrup is bubbing & boiling steadily while the rasgullas cook. Step 16 . Add the balls to the syrup. Step 17 . Keep the pan covered and boil for 9 to 10 mins. After 5 mins open the lid and gently stir the sugar syrup with a skewer without touching the rasgullas. This is for uniform cooking. Quickly cover and cook. Step 18 . Rasgullas will puff and double in size. The key step is to maintain the heat steadily. If the flame is too high, rasgulla may break. Step 19 . Rasgulla have doubled in size. Serve rasgulla chilled or at room temperature.",
    recipeSuggestion: " ",
},
{
  recipeId: 4,
  recipeName: "Pancake",
  recipeImage:<img src="http://yesofcorsa.com/wp-content/uploads/2017/11/4K-Pancakes-Photo.jpg" width="47.5%" height="30%" />,
  recipeIngredients: "1 cup all-purpose flour, 1 cup whole wheat flour, ½ cup powdered milk, 3 tablespoons white sugar, 2 tablespoons soy flour, 2 teaspoons baking powder, 1 teaspoon baking soda, ½ teaspoon salt, 1 ½ cups water, 2 tablespoons vegetable oil",
  recipePrepTime: "30 minutes",
  recipeMethod: "Step 1 . Mix all-purpose flour, whole wheat flour, powdered milk, sugar, soy flour, baking powder, baking soda, and salt together in a large bowl to make the batter. Step 2 . Combine 2 cups batter, water, and 2 tablespoons oil in a bowl. Add more or less water to reach your desired batter thickness. Mix well. Step 3 . Heat a lightly oiled griddle over medium-high heat. Drop batter by large spoonfuls onto the griddle and cook until bubbles form and the edges are dry, 3 to 4 minutes. Flip and cook until browned on the other side, 2 to 3 minutes. Repeat with remaining batter.",
  recipeSuggestion: "Pour some Honey or maple syrup on pan cakes or garnish it with some whipped cream and chocolate syrup." ,
},
{
  recipeId: 5,
  recipeName: "Aloo Paratha",
  recipeImage:<img src="https://i.ytimg.com/vi/0X1onzAOUc4/maxresdefault.jpg" width="47.5%" height="30%"/>,
  recipeIngredients: "Boiled medium sized potatoes – 5, Chopped onion – 1, Chopped green chili – 1, Roasted cumin powder – 1/2 tsp, Salt – as per taste, Red chili powder – 1/2 tbsp, Chopped cilantro – handful, Dried mango powder ( optional ) – 1/2 tsp, Whole wheat flour – 2 cups, Vegetable oil – 1 tsp, Salt – 1/4 teaspoon, Water – as required, Butter",
  recipePrepTime: "1 hour",
  recipeMethod: "Step 1 . In a large bowl strain whole wheat flour. Add, salt, oil & mix. Step 2 . Add water gradually according to requirement. Knead a semi soft dough & cover it a cloth. Step 3 . In a bowl mash boiled potatoes using masher, fork or hands. Add chopped onion, green chili, cilantro and mix. Step 4 . Add salt, cumin powder, dried mango powder, red chili powder & mix. Your potato stuffing is ready. Step 5 . Take a small portion out of the dough. Roll it to make a dough ball. Step 6 . Roll the dough ball a little & place the potato stuffing Step 7 . Make pleads by simply picking some dough & stick backward, repeat this process to make a stuffed dough ball. Step 8 . Put the stuffed dough ball in dusting flour & roll the paratha using a rolling pin. Step 9 . Heat a flat pan on medium flame & put the paratha & let it cook from one side for about 10 seconds, then flip it. Step 10 . After flipping the paratha let it cook for 10 seconds & then apply some oil or butter, cook it using spatula & take the paratha out on a dish plate.",
  recipeSuggestion: "Serve paratha with curd, curry, pickle or some butter along with any of your favorite tea." ,
},
{
  recipeId: 6,
  recipeName: "Fruit Salsa",
  recipeImage:<img src="https://bakerish.com/wp-content/uploads/2021/04/FRUIT-SALSA-2.webp" width="30%" height="15%"/>,
  recipeIngredients: "Strawberries, Blueberries, Pineapple, oranges, Kiwi, Honey, Lime juice, Lime zest, Granulated sugar, Ground cinnamon",
  recipePrepTime: "30 min",
  recipeMethod: " Step 1. Place the strawberries, blueberries, pineapple, mandarin oranges, and kiwi in a large bowl, set aside. Step 2. In a small bowl, whisk together the honey, lime juice, and lime zest until fully combined. Pour the sauce over the fruit in the bowl and toss to combine. Step 3. Fruit salsa is ready.",
  recipeSuggestion: "You can add your favourite fruits." ,
},
]